### ISSUE TITLE
Uncrafting While Using an Item

### ISSUE THREAD

**Issue by Antirhinnum** [Lanboost/TModLoader_LansUncraftItems#3]
When using an item with a long useTime (Such as the Magic Mirror), the player can still click on the Uncraft button, giving the player the components of the item whilst not consuming it in the process.
![Terraria_ Also try Edge of Space! 2019-10-27 08-47-59](https://user-images.githubusercontent.com/33076411/67634821-ea3a8f80-f896-11e9-99c6-b05533ec29e3.gif)

**Comment by Lanboost** [comment]
Nice Q/A testing!

This should be fixed with version v1.31.2

Closing the issue, if the issue persist with the new version please feel free to reopen a new ticket!

Regards Lan
