### ISSUE TITLE
Multi-Item Results

### ISSUE THREAD

**Issue by Antirhinnum** [Lanboost/TModLoader_LansUncraftItems#4]
No check is made to determine if a recipe creates more than one of an item. Thus, attempting to uncraft an item made in sets of 4 will allow for 4 separate uncraftings.
Ex: Use 1 Wood to make 4 Wood Wall. Uncraft all of the Wood Walls to receive ~4 wood back.
![Terraria_ Also try Edge of Space! 2019-10-27 08-58-29](https://user-images.githubusercontent.com/33076411/67634974-3e923f00-f898-11e9-9184-0302daee9f1a.gif)

**Comment by Lanboost** [comment]
This should be fixed with version v1.31.2

Closing the issue, if the issue persist with the new version please feel free to reopen a new ticket!

Regards Lan
