### ISSUE TITLE
Recipes Not Updating

### ISSUE THREAD

**Issue by Antirhinnum** [Lanboost/TModLoader_LansUncraftItems#5]
Items put into the inventory from uncrafting will not be counted in recipes until something else calls for recipes to be updated, such as a new item being added to the inventory or the player's adjTiles changes.
Ex: Uncraft any item (In this example, the Arctic Diving Gear). Even if both components are successfully returned and the player is standing near a Tinkerer's Workshop, the recipe for the Arctic Diving Gear does not show up until the player either changes the contents of their inventory or moves to another crafting station.
![Terraria_ Also try Edge of Space! 2019-10-27 09-07-06](https://user-images.githubusercontent.com/33076411/67635111-6209b980-f899-11e9-86df-dd320e492e73.gif)

**Comment by Lanboost** [comment]
This should be fixed with version v1.31.2

Closing the issue, if the issue persist with the new version please feel free to reopen a new ticket!

Regards Lan
