### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DAriusiotnzu** [Lanboost/TModLoader_LansUncraftItems#6]
It would be nice If you would add uncraft for multiple recipes,for example In my modpack I have the item Ice Skates and when I uncraft It I get 5 iron and 10 silk,but there Is another recipe that gives me 20 Ice block 5 iron and 5 leather.If you could add like an uncraft to recipe 1 or recipe 2 or recipe 3 that would be pretty nice,for now It just says using recipe 1 for now.Thanks for reading!
![image](https://user-images.githubusercontent.com/24359766/68089341-8c96dc00-fe70-11e9-853f-1492e1b7170c.png)

**Comment by Lanboost** [comment]
This should not be possible in latest version
