### ISSUE TITLE
Suggestion: Relocate or disable the recipe generator button 

### ISSUE THREAD

**Issue by AndreLouisIssa** [Lanboost/TModLoader_LansUncraftItems#8]
The recipe generation button is just not in the right place for how I'd prefer it to look but there's no config options to move it and you can't drag it.

I'd like it to be where the most recent achievement would appear or I'd like to totally hide it and just use a simple command or timer to refresh it.

Where it is now:
![image](https://user-images.githubusercontent.com/20250183/75438944-fe111200-59ac-11ea-8989-67b4a209c7dc.png)

Where I'd like it to be:
![image](https://user-images.githubusercontent.com/20250183/75439022-213bc180-59ad-11ea-9363-25912eedcaad.png)

**Comment by Lanboost** [comment]
In the latest version it should now be possible to move the button (other ui changes too)
